In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [39]:
import numpy as np
import matplotlib.pyplot as plt

In [40]:
from sklearn.datasets import load_digits
digits= load_digits()

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test= train_test_split(digits.data, digits.target, test_size=0.3)

In [42]:
# Ignoring all warnings

import warnings
warnings.filterwarnings('ignore')

In [43]:
# Using Log Regression evaluating performance

lr= LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9629629629629629

In [44]:
# Using SVM Algorithm

svm= SVC()
svm.fit(X_train, y_train)
svm.score(X_test,y_test)

0.9907407407407407

In [45]:
# Using Random Forest Algorithm

rf= RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9814814814814815

In [46]:
# K fold workings

from sklearn.model_selection import KFold
kf= KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [47]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [48]:
# Marking the model as function

def get_score(model,X_train, X_test,y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test,y_test)

In [49]:
get_score(LogisticRegression(), X_train, X_test,y_train, y_test)



0.9629629629629629

In [50]:
get_score(SVC(), X_train, X_test,y_train, y_test)

0.9907407407407407

In [51]:
get_score(RandomForestClassifier(), X_train, X_test,y_train, y_test)

0.9833333333333333

In [57]:
from sklearn.model_selection import StratifiedKFold
folds= StratifiedKFold(n_splits=3)

scores_logistic= []
scores_svm= []
scores_rf= []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test= digits.data[train_index],digits.data[test_index],\
                                   digits.target[train_index],digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

In [58]:
scores_logistic

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [59]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [60]:
scores_rf

[0.9332220367278798, 0.9465776293823038, 0.9265442404006677]

In [68]:
# This code will do the wonder in one line

from sklearn.model_selection import cross_val_score


In [69]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [64]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [67]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

array([0.91944444, 0.90833333, 0.95543175, 0.96100279, 0.92479109])

In [70]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93055556, 0.91944444, 0.95821727, 0.96100279, 0.9275766 ])

In [71]:
scores1= cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target, cv=10)
np.average(scores1)

0.879245810055866

In [72]:
scores2= cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target, cv=10)
np.average(scores2)

0.933227808814401

In [73]:
scores3= cross_val_score(RandomForestClassifier(n_estimators=30), digits.data, digits.target, cv=10)
np.average(scores3)

0.9393482309124768

In [76]:
scores4= cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target, cv=10)
np.average(scores4)

0.9432216014897579