In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df= pd.read_csv('homeprices.csv')
df.head(3)

area   price
0  2600  550000
1  3000  565000
2  3200  610000

In [5]:
model=linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression()

In [6]:
model.coef_

array([135.78767123])

In [7]:
model.intercept_

180616.43835616432

In [10]:
import warnings
warnings.filterwarnings('ignore')

In [11]:
model.predict([[5000]])

array([859554.79452055])

In [12]:
import pickle

### First Method

In [14]:
# saving the model using Pickle

with open('model_pickle','wb') as file:
    pickle.dump(model, file)

In [15]:
# Opening the file

with open ('model_pickle','rb') as f:
    mp=pickle.load(f)

In [16]:
mp.coef_

array([135.78767123])

In [17]:
mp.intercept_

180616.43835616432

In [21]:
mp.predict([[5000]])

array([859554.79452055])

### Second Method

In [27]:
# Using Joblib, if having more numpy arrays

import joblib



In [28]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [29]:
# Loading the same file

In [34]:
mj= joblib.load('model_joblib')


In [31]:
mj.coef_

array([135.78767123])

In [32]:
mj.intercept_

180616.43835616432

In [33]:
mj.predict([[5000]])

array([859554.79452055])